# alacritty themes
# https://github.com/alacritty/alacritty-theme

# online man pages
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.1.scd

#
# Appearance
#

[window]
# windows.opacity since version 0.10.0
opacity = 0.95

[window.dimensions]
columns = 140
lines = 48

#
# Fonts
#

[font]
size = 12
glyph_offset.x = 0
glyph_offset.y = 2
offset.x = 2
offset.y = 2

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

#
# Mouse config
#

# copy to clipboard on mouse selection
[selection]
save_to_clipboard = true